Lots of trying and testing to get the CI Action to work as I want it to. Still has many limitations and is subject to improvement, but it's a start.

diff --git a/.github/workflows/mate-ci.yml b/.github/workflows/mate-ci.yml
--- a/.github/workflows/mate-ci.yml
+++ b/.github/workflows/mate-ci.yml
@@ -23,6 +23,7 @@ jobs:
         #python-version: ["3.9", "3.10", "3.11", "3.12"]
         python-version: ["3.9"]  # DEV-TEMP: To save minutes while repo is not yet public!
 
+    # Setup
     steps:
     - uses: actions/checkout@v4
     - name: Set up Python ${{ matrix.python-version }}
@@ -33,12 +34,36 @@ jobs:
       run: |
         python -m pip install --upgrade pip
         python -m pip install ".[dev]"
-    - name: Code style formatting
+
+    # Code formatting
+    # DEV-TEMP: Instead of specifying src and test explicitly here, we could
+    # add an extend-exclude kwarg to pyproject.toml that stops black from
+    # looking at folders we don't want checked. But for now, I want folders 
+    # like prototype and macros excluded here, but not in pyproject.toml...
+    # Update: Seems like use_pyproject is only supported for python 3.11 or
+    # higher, so for now I guess this should stay as it is anyways.
+    - name: Code formatting with black
+      if: success() || failure()
+      uses: psf/black@stable
+      with:
+        src: "./src ./tests"
+        #use_pyproject: true  # Requires python 3.11 or higher
+    - name: Code formatting with isort
+      if: success() || failure()
       run: |
-        black src/
-        black tests/
-        isort src/
-        isort tests/
+        isort --check-only --diff ./src ./tests
+      # Using the isort action fails for an obscure reason...
+      #uses: isort/isort-action@v1
+      #with:
+      #  sort-paths: "./src ./tests"
+
+    # Testing
     - name: Test with pytest
+      if: success() || failure()
       run: |
         pytest
+    # TODO: Would be nice to have a good way of reporting the outcome of each
+    # test (as well as black and isort) in a report that gets automatically
+    # generated and posted on the PR. Seems like there's several tools for 
+    # doing this, but they don't seem to do exactly what I want, nor are they 
+    # straightforward. This is low-priority for now.
